// Auto-generated by scripts/sync-version.mjs — do not edit by hand
export const APP_VERSION = "0.1.0" as const
export const GRAPH_SCHEMA_VERSION = "1.1.0" as const
export const APP_CODENAME = "Scriptorium" as const
