/**
 * Sync version.json → all package.json files and apps/web/lib/app-meta.ts
 * Usage: npm run version:sync
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const meta = JSON.parse(readFileSync(join(root, "version.json"), "utf8"))

const packagePaths = [
  "package.json",
  "apps/web/package.json",
  "packages/graph-schema/package.json",
  "packages/narrative-engine/package.json",
  "packages/egoquest-fiction/package.json",
]

for (const rel of packagePaths) {
  const path = join(root, rel)
  const pkg = JSON.parse(readFileSync(path, "utf8"))
  pkg.version = meta.version
  writeFileSync(path, `${JSON.stringify(pkg, null, 2)}\n`)
}

const appMeta = `// Auto-generated by scripts/sync-version.mjs — do not edit by hand
export const APP_VERSION = "${meta.version}" as const
export const GRAPH_SCHEMA_VERSION = "${meta.schemaVersion}" as const
export const APP_CODENAME = "${meta.codename}" as const
`

writeFileSync(join(root, "apps/web/lib/app-meta.ts"), appMeta)
console.log(`Synced v${meta.version} (schema ${meta.schemaVersion})`)
